task: t2v
sampling_algo: longlive_flow_euler
data:
  data_dir:
    video_toy_data: data/video_toy_data
  external_caption_suffixes: [_Qwen2.5-VL]
  caption_proportion:
    prompt: 5
    _Qwen2_5-VL: 95
  external_data_filter:
    video_toy_data:
      _unimatch: {min: 1.0, max: 30}
  image_size: 480
  aspect_ratio_type: ASPECT_RATIO_VIDEO_480_MS
  motion_score_cal_type: average # average, max
  motion_score_file_thres:
    _unimatch: null
  load_text_feat: false
  load_vae_feat: false
  transform: default_train_video
  type: SanaZipDataset
  num_frames: 40
  sort_dataset: false
  resample_fps: false
  shuffle_dataset: true
image_data:
  data_dir:
    - data/toy_data
  image_size: 480
  external_caption_suffixes: []
  caption_selection_type: proportion
  caption_proportion:
    prompt: 1
  clip_thr_temperature: 0.1
  clip_thr: 25.0
  del_img_clip_thr: 22.0
  load_text_feat: false
  load_vae_feat: false
  transform: default_train
  type: SanaWebDatasetMS
  aspect_ratio_type: ASPECT_RATIO_VIDEO_480_MS
  sort_dataset: false
# model config
model:
  model: SanaMSVideo_2000M_P2_D20
  image_size: 480
  mixed_precision: bf16
  fp32_attention: true
  load_from: hf://Efficient-Large-Model/LongSANA_480p/checkpoints/LongSANA_480p.pth
  aspect_ratio_type: ASPECT_RATIO_VIDEO_480_MS
  multi_scale: true
  attn_type: cachedcausal
  linear_head_dim: 112
  ffn_type: CachedGLUMBConvTemp
  t_kernel_size: 3
  mlp_acts:
    - silu
    - silu
    -
  mlp_ratio: 3
  use_pe: true
  pos_embed_type: casual_wan_rope
  qk_norm: true
  cross_norm: true
  class_dropout_prob: 0.1
  chunk_index: null # start index of each chunk
# VAE setting
vae:
  vae_type: WanVAE
  vae_pretrained: hf://Efficient-Large-Model/SANA-Video_2B_480p/vae/Wan2.1_VAE.pth
  weight_dtype: float32
  vae_latent_dim: 16
  vae_downsample_rate: 8
  vae_stride:
    - 4
    - 8
    - 8
  if_cache: false
# text encoder
text_encoder:
  text_encoder_name: gemma-2-2b-it
  y_norm: true
  y_norm_scale_factor: 0.01
  model_max_length: 300
  # CHI
  chi_prompt:
    - 'Given a user prompt, generate an "Enhanced prompt" that provides detailed visual descriptions suitable for image generation. Evaluate the level of detail in the user prompt:'
    - '- If the prompt is simple, focus on adding specifics about colors, shapes, sizes, textures, and spatial relationships to create vivid and concrete scenes.'
    - '- If the prompt is already detailed, refine and enhance the existing details slightly without overcomplicating.'
    - 'Here are examples of how to transform or refine prompts:'
    - '- User Prompt: A cat sleeping -> Enhanced: A small, fluffy white cat curled up in a round shape, sleeping peacefully on a warm sunny windowsill, surrounded by pots of blooming red flowers.'
    - '- User Prompt: A busy city street -> Enhanced: A bustling city street scene at dusk, featuring glowing street lamps, a diverse crowd of people in colorful clothing, and a double-decker bus passing by towering glass skyscrapers.'
    - 'Please generate only the enhanced description for the prompt below and avoid including any additional commentary or evaluations:'
    - 'User Prompt: '
# Sana schedule Flow
scheduler:
  predict_flow_v: true
  noise_schedule: linear_flow
  pred_sigma: false
  flow_shift: 3.0
  inference_flow_shift: 7.0
  # logit-normal timestep
  weighting_scheme: logit_normal
  logit_mean: 0.0
  logit_std: 1.0
  vis_sampler: null
# training setting
train:
  chunk_sampling_strategy: incremental
  same_timestep_prob: 0.0
  ltx_image_condition_prob: 0.5
  use_fsdp: true
  joint_training_interval: 50
  num_workers: 10
  seed: 1
  train_batch_size: 1
  train_batch_size_image: 4
  num_epochs: 10
  gradient_accumulation_steps: 1
  grad_checkpointing: true
  gradient_clip: 0.1
  optimizer:
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-10
    lr: 5.0e-5
    type: AdamW
    weight_decay: 0.0
  lr_schedule: constant
  lr_schedule_args:
    num_warmup_steps: 500
  local_save_vis: true # if save log image locally
  visualize: true
  deterministic_validation: false
  eval_sampling_steps: 500
  log_interval: 5
  save_model_epochs: 5
  save_model_steps: 500
  work_dir: output/debug
  online_metric: false
  eval_metric_step: 2000
  online_metric_dir: metric_helper
  validation_images:
    - asset/example_data/00000000.png
  validation_prompts:
    - a cyberpunk cat with a neon sign that says "Sana".
